# Generated by Django 2.1.5 on 2019-01-12 14:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages.one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
    ]
