# Generated by Django 2.1.5 on 2019-01-12 14:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages.one', '0004_auto_20190112_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
