# Generated by Django 2.1.5 on 2019-01-12 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messages.one', '0006_auto_20190112_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 16, 46, 46, 789627, tzinfo=utc), verbose_name='date published'),
        ),
    ]
