# Generated by Django 2.1.5 on 2019-01-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages.one', '0008_auto_20190115_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
