# Generated by Django 2.1.5 on 2019-01-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages.one', '0009_auto_20190115_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mpoly',
        ),
    ]
