# Generated by Django 2.1.5 on 2019-01-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages.one', '0011_auto_20190115_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
