# Generated by Django 2.1.5 on 2019-01-15 20:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messages.one', '0012_auto_20190115_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=django_cryptography.fields.encrypt(models.TextField(max_length=1000)),
        ),
    ]
